DROP TABLE IF EXISTS USUARIO;

CREATE TABLE  "USUARIO" (
    "USERNAME" VARCHAR2(30) NOT NULL PRIMARY KEY,
	"NOMBRE" VARCHAR2(20) NOT NULL,
	"APELLIDO" VARCHAR2(20),
	"EMAIL" VARCHAR2(35) NOT NULL,
	"EDAD" NUMBER NOT NULL,
	"PASSWORD" VARCHAR2(20) NOT NULL

);

